<MyApp>:
    BoxLayout:
        orientation: 'vertical'
        id:chemical
        canvas.before:
            Color:
                rgba: 32/255, 49/255, 65/255, 1  # Light blue color (R, G, B, A)
            Rectangle:
                pos: self.pos
                size: self.size
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: .2
            height: 40
            pos_hint: {'top': 1}
            canvas.before:
                Color:
                    rgba: 32/255, 49/255, 65/255, 1  # RGB normalized
                Rectangle:
                    pos: self.pos
                    size: self.size
            BoxLayout:
                padding:40
                spacing : 20
                size_hint: None, None
                size: 400, 70
                pos_hint: {'center_y': 0.67, 'center_x': 0.1}
                canvas.before:
                    Color:
                        rgba: 1, 1, 1, 1
                    Rectangle:
                        source: 'logo.png'
                        pos: self.pos
                        size: self.size
            FloatLayout:
                orientation: 'horizontal'
                size_hint:(1,.1)
                height: 40
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                background_color:(32/255, 49/255, 75/255, 1)

                MDIconButton:
                    icon:'home-circle-outline'
                    id:home
                    theme_text_color: 'Custom'
                    text_color: [1, 1, 1, 1]
                    icon_size:'70sp'
                    on_release:app.chem_delay_fn('switch_to_main')
                    pos_hint: {'center_x':0.96, 'center_y': 0.8}
                    radius: [50, 50, 50, 50]

        BoxLayout:
            orientation: 'horizontal'
            size_hint: 1, .3
            spacing:10
            padding:10
            BoxLayout:
                orientation: 'vertical'
                pos_hint: {'center_x': 0.1, 'center_y': 0.9}
                size_hint : .4,1
                padding:100
                GridLayout:
                    cols:1
                    padding:10

                    Label:
                        text: 'Valve No'
                        size_hint: None, None
                        size: 100, 50
                        font_size : 42
                        bold : True
                    Label:
                        text: ''
                        id: valve_no
                        size_hint: None, None
                        size: 100, 50
                        font_size : 42
                        bold : True

            BoxLayout:
                orientation:'vertical'
                spacing:10
                padding:10
                pos_hint: {'center_x': .5, 'center_y': 0.5}
                GridLayout:
                    cols: 4
                    spacing:20
                    padding:30

                    Label:
                        text: 'Chemical Name'
                        size_hint: None, None
                        size: 200, 30
                        font_size:17
                        bold:True
                        text_size:self.size
                        halign:'center'
                        valign:'middle'

                    Label:
                        text:'Stock'
                        size_hint: None, None
                        size: 200, 30
                        font_size:17
                        bold:True
                        text_size:self.size
                        halign:'center'
                        valign:'middle'

                    Label:
                        text:'Min Stock'
                        size_hint: None, None
                        size: 200, 30
                        font_size:17
                        bold:True
                        text_size:self.size
                        halign:'center'
                        valign:'middle'

                    Label:
                        text:'Input Path'
                        size_hint: None, None
                        size: 200, 30
                        font_size:17
                        bold:True
                        text_size:self.size
                        halign:'center'
                        valign:'middle'

                    Label:
                        id: chemical_name
                        size_hint: None, None
                        size: 200, 30
                        readonly:True
                        color:(0,0,0,1)
                        canvas.before:
                            Color:
                                rgba: 1, 1, 1, 1  # red
                            Rectangle:
                                pos: self.pos
                                size: self.size


                    Label:
                        id:stockchem
                        size_hint: None, None
                        size: 200, 30
                        readonly:True
                        color:(0,0,0,1)
                        canvas.before:
                            Color:
                                rgba: 1, 1, 1, 1  # red
                            Rectangle:
                                pos: self.pos
                                size: self.size

                    Label:

                        id:min_stock
                        size_hint: None, None
                        size: 200, 30
                        readonly:True
                        color:(0,0,0,1)
                        canvas.before:
                            Color:
                                rgba: 1, 1, 1, 1  # red
                            Rectangle:
                                pos: self.pos
                                size: self.size


                    Label:

                        id:input_path
                        size_hint: None, None
                        size: 200, 30
                        readonly:True
                        color:(0,0,0,1)
                        canvas.before:
                            Color:
                                rgba: 1, 1, 1, 1  # red
                            Rectangle:
                                pos: self.pos
                                size: self.size
                BoxLayout:
                    orientation:'horizontal'
                    Label:

                        size_hint: None, None
                        size: 300, 30
                    Label:
                        text: 'Caution: Do not change without Manufacturer approval'
                        color: 1, 0, 0, 1  # Red color (R, G, B, A)
                        size_hint: None, None
                        size: 300, 30
                        font_size:17
                        bold:True
            BoxLayout:
                orientation:'vertical'
                spacing:10
                padding:10
                size_hint:.5,1
                pos_hint: {'center_x': 0.1, 'center_y': 0.9}
                MDRectangleFlatIconButton:
                    text: 'Save'
                    id:save_button
                    font_style: 'H6'
                    size_hint: None, None
                    size: 150, 30
                    icon: 'content-save'
                    icon_color: [1, 1, 1, 1]  # Light grey color
                    font_size: '16dp'
                    text_color: [1, 1, 1, 1]
                    md_bg_color: [0.3, 0.3, 0.3, 1]
                    on_release: app.save_changes()
                    on_press: app.change_button_color(self)


        ScrollView:  # Wrap your GridLayout with a ScrollView
            GridLayout:
                id: chemical_grid
                cols: 11
                size_hint_y: None
                height: self.minimum_height


